version: '2'
services:
    ex1jhipster-app:
        image: ex1jhipster
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ex1jhipster-mysql:3306/ex1jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ex1jhipster-elasticsearch:9300
        ports:
            - 8080:8080
    ex1jhipster-mysql:
        extends:
            file: mysql.yml
            service: ex1jhipster-mysql
    ex1jhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ex1jhipster-elasticsearch
